---  
- name: Install common packages
  become: true
  apt:
    name: ['tree', 'vim', 'git', 'htop','bzip2', 'unzip', 'wget', 'curl', 'lsof', 'net-tools', 'netcat', 'nmap']
    update_cache: yes
    state: present
    install_recommends: no
